'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RelAmb02.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''Liebe Versuchsperson, \par \par
        '''
        '''vielen Dank für Ihre Teilnahme an dieser Studie! \par \par \par
        '''
        '''Die Studie wird aus mehreren Aufgaben bestehen, die Sie nacheinander bearbeiten. \par \par
        '''Bitte lesen Sie die Instruktionen immer aufmerksam durch! \par \par \par \par
        '''
        '''Starten Sie mit dem ersten Teil der Studie, indem Sie den &quot;Weiter&quot;-Button drücken.
        '''}.
        '''</summary>
        Friend ReadOnly Property _0_mainInstr() As String
            Get
                Return ResourceManager.GetString("_0_mainInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''In diesem Teil bitten wir Sie, über sogenannte &quot;signifikante Andere&quot; in Ihrem Leben nachzudenken. \par \par
        '''Damit sind wichtige Bezugspersonen gemeint, die einen grössen Einfluss auf Ihr Leben nehmen. \par
        '''Dies können beispielsweise (Ex-)Partner, Geschwister, Eltern, oder Freunde sein. \par \par \par
        '''
        '''Sie werden gebeten, die Vornamen von 4 dieser Art von signifikanten anderen anzugeben. \par
        '''Bitte stellen Sie sicher, dass Sie 4 eindeutige, unterschiedliche Namen ne [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _1_collectObjects() As String
            Get
                Return ResourceManager.GetString("_1_collectObjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \qc
        '''Bitte geben Sie die Namen von zwei {\b unbeliebten} Personen ein. \par \par
        '''
        '''Denken Sie an zwei &quot;signifikante Personen&quot;, die Sie {\b am wenigsten} mögen. \par
        '''Menschen in Ihrem Leben, bei denen Sie sich {\b nicht sehr gut fühlen}, \par
        '''und denen gegenüber Sie {\b negative} Gefühle hegen.
        '''}.
        '''</summary>
        Friend ReadOnly Property _1_collectObjectsNeg() As String
            Get
                Return ResourceManager.GetString("_1_collectObjectsNeg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \qc
        '''Bitte geben Sie die Namen von zwei {\b beliebten} Personen ein. \par \par
        '''
        '''Denken Sie an zwei &quot;signifikante Personen&quot;, die Sie {\b am meisten} mögen. \par
        '''Menschen in Ihrem Leben, bei denen Sie sich {\b sehr gut fühlen}, \par
        '''und denen gegenüber Sie {\b positive} Gefühle hegen.
        '''}.
        '''</summary>
        Friend ReadOnly Property _1_collectObjectsPos() As String
            Get
                Return ResourceManager.GetString("_1_collectObjectsPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''In diesem Teil bitten wir Sie, über sogenannte &quot;signifikante Andere&quot; in Ihrem Leben nachzudenken. \par \par
        '''Damit sind wichtige Bezugspersonen gemeint, die einen grössen Einfluss auf Ihr Leben nehmen. \par
        '''Dies können beispielsweise (Ex-)Partner, Geschwister, Eltern, oder Freunde sein. \par \par \par
        '''
        '''Sie werden gebeten, die Vornamen von 4 dieser Art von signifikanten anderen anzugeben. \par
        '''Bitte stellen Sie sicher, dass Sie 4 eindeutige, unterschiedliche Namen ne [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _1_collectOthers() As String
            Get
                Return ResourceManager.GetString("_1_collectOthers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \qc
        '''Bitte geben Sie die Namen von zwei {\b unbeliebten} Personen ein. \par \par
        '''
        '''Denken Sie an zwei &quot;signifikante Personen&quot;, die Sie {\b am wenigsten} mögen. \par
        '''Menschen in Ihrem Leben, bei denen Sie sich {\b nicht sehr gut fühlen}, \par
        '''und denen gegenüber Sie {\b negative} Gefühle hegen.
        '''}.
        '''</summary>
        Friend ReadOnly Property _1_collectOthersNeg() As String
            Get
                Return ResourceManager.GetString("_1_collectOthersNeg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \qc
        '''Bitte geben Sie die Namen von zwei {\b beliebten} Personen ein. \par \par
        '''
        '''Denken Sie an zwei &quot;signifikante Personen&quot;, die Sie {\b am meisten} mögen. \par
        '''Menschen in Ihrem Leben, bei denen Sie sich {\b sehr gut fühlen}, \par
        '''und denen gegenüber Sie {\b positive} Gefühle hegen.
        '''}.
        '''</summary>
        Friend ReadOnly Property _1_collectOthersPos() As String
            Get
                Return ResourceManager.GetString("_1_collectOthersPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \qc
        '''In der folgenden Phase möchten wir untersuchen, wie schnell Menschen die Valenz von Wörtern feststellen können. \par
        '''Damit ist gemeint, wie schnell Menschen darin sind, \par ein präsentiertes Wort als &quot;positiv&quot; oder &quot;negativ&quot; zu klassifizieren. \par \par
        '''
        '''Im Zuge jeder einzelnen Klassifizierung werden Sie zwei Wörter sehen. \par
        '''Das erste Wort wird nur sehr kurz auf dem Bildschirm zu sehen sein, unter Umständen sogar so kurz, \par dass Sie nicht in der Lage sind, es zu identifizier [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_practiceObjectsAneg() As String
            Get
                Return ResourceManager.GetString("_2_practiceObjectsAneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \qc
        '''In der folgenden Phase möchten wir untersuchen, wie schnell Menschen die Valenz von Wörtern feststellen können. \par
        '''Damit ist gemeint, wie schnell Menschen darin sind, \par ein präsentiertes Wort als &quot;positiv&quot; oder &quot;negativ&quot; zu klassifizieren. \par \par
        '''
        '''Im Zuge jeder einzelnen Klassifizierung werden Sie zwei Wörter sehen. \par
        '''Das erste Wort wird nur sehr kurz auf dem Bildschirm zu sehen sein, unter Umständen sogar so kurz, \par dass Sie nicht in der Lage sind, es zu identifizier [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_practiceObjectsApos() As String
            Get
                Return ResourceManager.GetString("_2_practiceObjectsApos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \qc
        '''In der folgenden Phase möchten wir untersuchen, wie schnell Menschen die Valenz von Wörtern feststellen können. \par
        '''Damit ist gemeint, wie schnell Menschen darin sind, \par ein präsentiertes Wort als &quot;positiv&quot; oder &quot;negativ&quot; zu klassifizieren. \par \par
        '''
        '''Im Zuge jeder einzelnen Klassifizierung werden Sie zwei Wörter sehen. \par
        '''Das erste Wort wird nur sehr kurz auf dem Bildschirm zu sehen sein, unter Umständen sogar so kurz, \par dass Sie nicht in der Lage sind, es zu identifizier [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_practiceOthersAneg() As String
            Get
                Return ResourceManager.GetString("_2_practiceOthersAneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \qc
        '''In der folgenden Phase möchten wir untersuchen, wie schnell Menschen die Valenz von Wörtern feststellen können. \par
        '''Damit ist gemeint, wie schnell Menschen darin sind, \par ein präsentiertes Wort als &quot;positiv&quot; oder &quot;negativ&quot; zu klassifizieren. \par \par
        '''
        '''Im Zuge jeder einzelnen Klassifizierung werden Sie zwei Wörter sehen. \par
        '''Das erste Wort wird nur sehr kurz auf dem Bildschirm zu sehen sein, unter Umständen sogar so kurz, \par dass Sie nicht in der Lage sind, es zu identifizier [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_practiceOthersApos() As String
            Get
                Return ResourceManager.GetString("_2_practiceOthersApos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Sie haben die Übungsphase nun beendet. \par \par
        '''
        '''Als nächstes folgt die Testphase, welche identisch zur Übungsphase ist, aber länger dauert. \par \par
        '''
        '''Die Zuteilung der Tasten zu &quot;positiv&quot; und &quot;negativ&quot; bleibt ebenfalls genauso wie in der Übungsphase: \par \par
        '''
        '''Drücken Sie bitte die Taste &quot;A&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;negativ&quot; ist. \par
        '''Drücken Sie bitte die Taste &quot;L&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;positiv&quot; ist. \par \par        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3_experimentObjectsAneg() As String
            Get
                Return ResourceManager.GetString("_3_experimentObjectsAneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Sie haben die Übungsphase nun beendet. \par \par
        '''
        '''Als nächstes folgt die Testphase, welche identisch zur Übungsphase ist, aber länger dauert. \par \par
        '''
        '''Die Zuteilung der Tasten zu &quot;positiv&quot; und &quot;negativ&quot; bleibt ebenfalls genauso wie in der Übungsphase: \par \par
        '''
        '''Drücken Sie bitte die Taste &quot;A&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;positiv&quot; ist. \par
        '''Drücken Sie bitte die Taste &quot;L&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;negativ&quot; ist. \par \par        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3_experimentObjectsApos() As String
            Get
                Return ResourceManager.GetString("_3_experimentObjectsApos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Sie haben die Übungsphase nun beendet. \par \par
        '''
        '''Als nächstes folgt die Testphase, welche identisch zur Übungsphase ist, aber länger dauert. \par \par
        '''
        '''Die Zuteilung der Tasten zu &quot;positiv&quot; und &quot;negativ&quot; bleibt ebenfalls genauso wie in der Übungsphase: \par \par
        '''
        '''Drücken Sie bitte die Taste &quot;A&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;negativ&quot; ist. \par
        '''Drücken Sie bitte die Taste &quot;L&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;positiv&quot; ist. \par \par        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3_experimentOthersAneg() As String
            Get
                Return ResourceManager.GetString("_3_experimentOthersAneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Sie haben die Übungsphase nun beendet. \par \par
        '''
        '''Als nächstes folgt die Testphase, welche identisch zur Übungsphase ist, aber länger dauert. \par \par
        '''
        '''Die Zuteilung der Tasten zu &quot;positiv&quot; und &quot;negativ&quot; bleibt ebenfalls genauso wie in der Übungsphase: \par \par
        '''
        '''Drücken Sie bitte die Taste &quot;A&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;positiv&quot; ist. \par
        '''Drücken Sie bitte die Taste &quot;L&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;negativ&quot; ist. \par \par        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3_experimentOthersApos() As String
            Get
                Return ResourceManager.GetString("_3_experimentOthersApos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''
        '''
        '''YOU HAVE COMPLETED THE FIRST BLOCK, YOU CAN HAVE A SHORT BREAK, THEN CONTINUE ON
        '''?? EXACT WORDING??
        '''
        '''
        '''}.
        '''</summary>
        Friend ReadOnly Property _3b_breakInstr() As String
            Get
                Return ResourceManager.GetString("_3b_breakInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Sie haben die Klassifizierungsphase nun beendet. \par \par
        '''
        '''Wir möchten, dass Sie einige Fragen zu Ihren &quot;signifikanten Anderen&quot; und &quot;signifikanten Objekten&quot; beantworten, die Sie uns zu Beginn des Experiments genannt haben. \par \par
        '''
        '''Wichtig: Ziehen Sie den Schieber einfach mit der Maus zur gewünschten Position auf der Skala. \par \par \par
        '''
        '''Drücken Sie den &quot;Weiter&quot;-Button um fortzufahren.
        '''}.
        '''</summary>
        Friend ReadOnly Property _4_explicitInstr() As String
            Get
                Return ResourceManager.GetString("_4_explicitInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Wir bitten Sie noch ein paar Angaben zu Ihrer Person zu machen. \par \par \par
        '''
        '''Drücken Sie den &quot;Weiter&quot;-Button um fortzufahren.
        '''}.
        '''</summary>
        Friend ReadOnly Property _5_demoInstr() As String
            Get
                Return ResourceManager.GetString("_5_demoInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \qc
        '''
        '''
        '''WE WOULD LIKE YOU TO SHORTLY THINK ABOUT WORDS THAT YOU FIND AMBIVALENT.
        '''WRITE THEM DOWN IN THE BOX BELOW (OR SOMETHING LIKE THIS)
        '''
        '''
        '''}.
        '''</summary>
        Friend ReadOnly Property _6_ambiInstr() As String
            Get
                Return ResourceManager.GetString("_6_ambiInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \qc
        '''Das Experiment ist nun beendet. \par \par
        '''
        '''Nochmals vielen Dank für Ihre Teilnahme! \par \par \par
        '''
        '''Wenden Sie sich bitte an die Versuchsleitung.
        '''}.
        '''</summary>
        Friend ReadOnly Property _7_endInstr() As String
            Get
                Return ResourceManager.GetString("_7_endInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 111 100 010 000 011 110 001 101 100 110 101 111 010 001 011 000 101 110 010 111 001 100 011 000 101 011 000 001 010 111 100 110 000 111 100 010 011 001 101 110 100 010 011 110 101 111 000 001 010 101 110 111 011 001 100 000 111 101 001 100 010 000 011 110 111 010 011 100 101 001 110 000 001 000 110 010 011 100 101 111 011 111 100 010 110 101 000 001 011 110 001 000 101 010 111 100 000 100 001 111 010 101 011 110 001 011 000 010 110 111 101 100 111 100 011 001 010 110 000 101 100 101 111 011 000 110 001 010  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BlockRandomisation() As String
            Get
                Return ResourceManager.GetString("BlockRandomisation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Leid Feind Streit Drohung Abschied Gefängnis Verbrechen.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Neg() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mut Lust Glück Freude Frieden Hoffnung Vertrauen Wochenende.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Pos() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lpq Pgn Xbz Srj Fmhj Qpqd Tpfk Mqvl Hhwcj Pdvgw Rpxvk Rvhgl Sckrfl Snxwhv Wgwpkt Zcknhr Tkspzcg Lkxfstq Sskfblx Wmrzbnq Fkmrzdhs Mbdrfnmj Hvklxrhs Ldcfmxkz Lzhxpjtrf Vpwndzmsl Stglnwcbv Blvqxsjph Qmtcqswzfv Dpkbgrsvqj Jkvntxljph Nlvsngqpwx.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Str() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BRUTAL EINSAM ELEND GRAUSAM ILLEGAL KRANK TRAGISCH TRAURIG.
        '''</summary>
        Friend ReadOnly Property experimentTarget_Neg() As String
            Get
                Return ResourceManager.GetString("experimentTarget_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BELIEBT GENIAL GESUND LEBENDIG OPTIMAL PERFEKT SONNIG SUPER.
        '''</summary>
        Friend ReadOnly Property experimentTarget_Pos() As String
            Get
                Return ResourceManager.GetString("experimentTarget_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property iconExp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("iconExp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Achim Dana Hannelore Kaspar Nicolaus Valerie.
        '''</summary>
        Friend ReadOnly Property practiceOthers() As String
            Get
                Return ResourceManager.GetString("practiceOthers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mord Angst Sklave.
        '''</summary>
        Friend ReadOnly Property practicePrime_Neg() As String
            Get
                Return ResourceManager.GetString("practicePrime_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kuss Idee Chance.
        '''</summary>
        Friend ReadOnly Property practicePrime_Pos() As String
            Get
                Return ResourceManager.GetString("practicePrime_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lpqmf Pxbzqnh.
        '''</summary>
        Friend ReadOnly Property practicePrime_Str() As String
            Get
                Return ResourceManager.GetString("practicePrime_Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BOSHAFT KORRUPT UNGERECHT GEHÄSSIG.
        '''</summary>
        Friend ReadOnly Property practiceTarget_Neg() As String
            Get
                Return ResourceManager.GetString("practiceTarget_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GEDULDIG ZÄRTLICH HUMORVOLL FLEISSIG.
        '''</summary>
        Friend ReadOnly Property practiceTarget_Pos() As String
            Get
                Return ResourceManager.GetString("practiceTarget_Pos", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
