'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RelAmb02.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''Liebe Versuchsperson, \par \par
        '''
        '''vielen Dank für Ihre Teilnahme an dieser Studie! \par \par \par
        '''
        '''Die Studie wird aus mehreren Aufgaben bestehen, die Sie nacheinander bearbeiten werden. \par \par
        '''Bitte lesen Sie sich die Instruktionen immer aufmerksam durch! \par \par \par \par
        '''
        '''Starten Sie mit dem ersten Teil der Studie, indem Sie den &quot;Weiter&quot;-Button drücken.
        '''}.
        '''</summary>
        Friend ReadOnly Property _0_mainInstr() As String
            Get
                Return ResourceManager.GetString("_0_mainInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''In diesem Teil bitten wir Sie, über wichtige {\b Objekte} in Ihrem Leben nachzudenken. \par \par
        '''Damit sind Dinge gemeint, die einen großen Einfluss auf Ihr Leben nehmen. \par
        '''Dies können beispielsweise persönliche oder oft genutzte Gegenstände, Nahrungsmittel, Pflanzen,... sein. \par \par \par
        '''
        '''Sie werden gebeten, die Bezeichnungen von 4 solcher wichtigen Dinge anzugeben. \par
        '''Bitte geben Sie jedes als ein einzelnes Wort ein. \par \par \par
        '''Bitte stellen Sie sich [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _1_collectObjects() As String
            Get
                Return ResourceManager.GetString("_1_collectObjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \qc
        '''
        '''Bitte geben Sie die Bezeichnungen von zwei wichtigen Objekten an,\par
        ''' die Sie {\b am wenigsten} mögen. \par \par
        '''Gemeint sind Objekte in Ihrem Leben, die Sie {\b nicht sehr gut finden} \par
        '''und denen gegenüber Sie {\b negative} Gefühle hegen.
        '''}.
        '''</summary>
        Friend ReadOnly Property _1_collectObjectsNeg() As String
            Get
                Return ResourceManager.GetString("_1_collectObjectsNeg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \qc
        '''
        '''Bitte geben Sie die Bezeichnungen von zwei wichtigen Objekten an,\par
        ''' die Sie {\b am meisten} mögen. \par \par
        '''Gemeint sind Objekte in Ihrem Leben, die Sie {\b sehr gut finden} \par
        '''und denen gegenüber Sie {\b positive} Gefühle hegen.
        '''}.
        '''</summary>
        Friend ReadOnly Property _1_collectObjectsPos() As String
            Get
                Return ResourceManager.GetString("_1_collectObjectsPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''In diesem Teil bitten wir Sie, über wichtige {\b Personen} in Ihrem Leben nachzudenken. \par \par
        '''Damit sind Bezugspersonen gemeint, die einen großen Einfluss auf Ihr Leben nehmen. \par
        '''Dies können beispielsweise (Ex-)Partner, Familienmitglieder, Freunde, Konkurrenten,... sein. \par \par \par
        '''
        '''Sie werden gebeten, die Vornamen von 4 solcher wichtigen Personen anzugeben. \par
        '''Bitte geben Sie jedes als ein einzelnes Wort ein. \par \par \par
        '''Bitte stellen Sie sicher,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _1_collectOthers() As String
            Get
                Return ResourceManager.GetString("_1_collectOthers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \qc
        '''
        '''Bitte geben Sie die Namen von zwei wichtigen Personen an, die Sie {\b am wenigsten} mögen. \par \par
        '''Gemeint sind Menschen in Ihrem Leben, bei denen Sie sich {\b nicht sehr gut fühlen} \par
        '''und denen gegenüber Sie {\b negative} Gefühle hegen.
        '''}.
        '''</summary>
        Friend ReadOnly Property _1_collectOthersNeg() As String
            Get
                Return ResourceManager.GetString("_1_collectOthersNeg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \qc
        '''
        '''Bitte geben Sie die Namen von zwei wichtigen Personen an, die Sie {\b am meisten} mögen. \par \par
        '''Gemeint sind Menschen in Ihrem Leben, bei denen Sie sich {\b sehr gut fühlen} \par
        '''und denen gegenüber Sie {\b positive} Gefühle hegen.
        '''}.
        '''</summary>
        Friend ReadOnly Property _1_collectOthersPos() As String
            Get
                Return ResourceManager.GetString("_1_collectOthersPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \qc
        '''In der folgenden Phase möchten wir untersuchen, wie schnell Menschen \par 
        '''ein präsentiertes Wort als &quot;positiv&quot; oder &quot;negativ&quot; einordnen können. \par \par
        '''
        '''Im Zuge jedes einzelnen Durchgangs werden Sie zwei Wörter sehen. \par
        '''Das erste Wort wird nur kurz auf dem Bildschirm zu sehen sein. \par \par
        '''Das zweite Wort, das kurz nach dem ersten in GROSSBUCHSTABEN dargestellt wird, ist am wichtigsten. \par
        '''Das zweite Wort wird so lange zu sehen sein, bis Sie es entweder als &quot;positiv&quot; od [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_practiceAneg() As String
            Get
                Return ResourceManager.GetString("_2_practiceAneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \qc
        '''In der folgenden Phase möchten wir untersuchen, wie schnell Menschen \par 
        '''ein präsentiertes Wort als &quot;positiv&quot; oder &quot;negativ&quot; einordnen können. \par \par
        '''
        '''Im Zuge jedes einzelnen Durchgangs werden Sie zwei Wörter sehen. \par
        '''Das erste Wort wird nur kurz auf dem Bildschirm zu sehen sein. \par \par
        '''Das zweite Wort, das kurz nach dem ersten in GROSSBUCHSTABEN dargestellt wird, ist am wichtigsten. \par
        '''Das zweite Wort wird so lange zu sehen sein, bis Sie es entweder als &quot;positiv&quot; od [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2_practiceApos() As String
            Get
                Return ResourceManager.GetString("_2_practiceApos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''
        '''Sie haben nun den ersten Block beendet.\par
        '''Sie können nun eine kurze Pause machen.\par \par
        '''
        '''Danach folgt ein weiterer Block. \par
        '''Dieser wird ebenso aus einem kurzen Übungsdurchgang und einer etwas längeren Testphase bestehen.\par \par
        '''
        '''Wenn Sie bereit sind, fahren Sie mit dem &quot;Weiter&quot;-Button fort. \par
        '''
        '''}.
        '''</summary>
        Friend ReadOnly Property _3_breakInstr() As String
            Get
                Return ResourceManager.GetString("_3_breakInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Sie haben die Übungsphase nun beendet. \par \par
        '''
        '''Als nächstes folgt die Testphase. Diese wird circa 7 Minuten dauern und ist ansonsten identisch zur Übungsphase. \par \par
        '''
        '''Die Zuteilung der Tasten zu &quot;positiv&quot; und &quot;negativ&quot; bleibt ebenfalls genauso wie in der Übungsphase: \par \par
        '''
        '''Drücken Sie bitte die Taste &quot;A&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;negativ&quot; ist. \par
        '''Drücken Sie bitte die Taste &quot;L&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;pos [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3_experimentAneg() As String
            Get
                Return ResourceManager.GetString("_3_experimentAneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Sie haben die Übungsphase nun beendet. \par \par
        '''
        '''Als nächstes folgt die Testphase. Diese wird circa 7 Minuten dauern und ist ansonsten identisch zur Übungsphase. \par \par
        '''
        '''Die Zuteilung der Tasten zu &quot;positiv&quot; und &quot;negativ&quot; bleibt ebenfalls genauso wie in der Übungsphase: \par \par
        '''
        '''Drücken Sie bitte die Taste &quot;A&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;positiv&quot; ist. \par
        '''Drücken Sie bitte die Taste &quot;L&quot; auf Ihrer Tastatur, wenn das präsentierte Wort &quot;neg [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3_experimentApos() As String
            Get
                Return ResourceManager.GetString("_3_experimentApos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Vielen Dank! Sie haben die Aufgaben zur Einordnung nun beendet. \par \par
        '''
        '''Wir möchten Sie nun bitten, einige Fragen zu den wichtigen Personen und Objekten in Ihrem Leben, \par
        '''die Sie uns zu Beginn des Experiments genannt haben, zu beantworten. \par \par
        '''
        '''Dafür ziehen Sie den Schieber einer Skale einfach mit der Maus zur gewünschten Position. \par \par \par
        '''
        '''Drücken Sie den &quot;Weiter&quot;-Button um fortzufahren.
        '''}.
        '''</summary>
        Friend ReadOnly Property _4_explicitInstr() As String
            Get
                Return ResourceManager.GetString("_4_explicitInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \par \qc
        '''Wir bitten Sie noch ein paar Angaben zu Ihrer Person zu machen. \par \par \par
        '''
        '''Drücken Sie den &quot;Weiter&quot;-Button um fortzufahren.
        '''}.
        '''</summary>
        Friend ReadOnly Property _5_demoInstr() As String
            Get
                Return ResourceManager.GetString("_5_demoInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \qc
        '''
        '''Wir möchten Sie im folgenden bitten einige Wörter aufzuschreiben, die für Sie {\b ambivalent} sind. \par
        '''Das bedeutet, dass diese für Sie sowohl &quot;positiv&quot;, als auch &quot;negativ&quot; zugleich sind. \par \par
        '''
        '''Nennen Sie dabei bitte {\b Nomen}, für deren Bedeutung Sie sowohl &quot;positive&quot;, als auch &quot;negative&quot; Gefühle hegen. \par \par
        '''Schreiben Sie diese bitte in den unten stehenden Kasten. \par
        '''
        '''
        '''}.
        '''</summary>
        Friend ReadOnly Property _6_ambiInstr() As String
            Get
                Return ResourceManager.GetString("_6_ambiInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi \par \par \par \qc
        '''Das Experiment ist hiermit beendet. \par \par
        '''
        '''Nochmals vielen Dank für Ihre Teilnahme! \par \par \par
        '''
        '''Wenden Sie sich nun bitte an die Versuchsleitung.
        '''}.
        '''</summary>
        Friend ReadOnly Property _7_endInstr() As String
            Get
                Return ResourceManager.GetString("_7_endInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 111 100 010 000 011 110 001 101 100 110 101 111 010 001 011 000 101 110 010 111 001 100 011 000 101 011 000 001 010 111 100 110 000 111 100 010 011 001 101 110 100 010 011 110 101 111 000 001 010 101 110 111 011 001 100 000 111 101 001 100 010 000 011 110 111 010 011 100 101 001 110 000 001 000 110 010 011 100 101 111 011 111 100 010 110 101 000 001 011 110 001 000 101 010 111 100 000 100 001 111 010 101 011 110 001 011 000 010 110 111 101 100 111 100 011 001 010 110 000 101 100 101 111 011 000 110 001 010  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BlockRandomisation() As String
            Get
                Return ResourceManager.GetString("BlockRandomisation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Leid Feind Streit Drohung Abschied Gefängnis Verbrechen.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Neg() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mut Lust Glück Freude Frieden Hoffnung Vertrauen Wochenende.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Pos() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lpq Pgn Xbz Srj Fmhj Qpqd Tpfk Mqvl Hhwcj Pdvgw Rpxvk Rvhgl Sckrfl Snxwhv Wgwpkt Zcknhr Tkspzcg Lkxfstq Sskfblx Wmrzbnq Fkmrzdhs Mbdrfnmj Hvklxrhs Ldcfmxkz Lzhxpjtrf Vpwndzmsl Stglnwcbv Blvqxsjph Qmtcqswzfv Dpkbgrsvqj Jkvntxljph Nlvsngqpwx.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Str() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BRUTAL EINSAM ELEND GRAUSAM ILLEGAL KRANK TRAGISCH TRAURIG.
        '''</summary>
        Friend ReadOnly Property experimentTarget_Neg() As String
            Get
                Return ResourceManager.GetString("experimentTarget_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BELIEBT GENIAL GESUND LEBENDIG OPTIMAL PERFEKT SONNIG SUPER.
        '''</summary>
        Friend ReadOnly Property experimentTarget_Pos() As String
            Get
                Return ResourceManager.GetString("experimentTarget_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property iconExp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("iconExp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Horoskop Kaktus Ordner Pinzette Schnecke Uhr.
        '''</summary>
        Friend ReadOnly Property practiceObjects() As String
            Get
                Return ResourceManager.GetString("practiceObjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Achim Dana Hannelore Kaspar Nicolaus Valerie.
        '''</summary>
        Friend ReadOnly Property practiceOthers() As String
            Get
                Return ResourceManager.GetString("practiceOthers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mord Angst Sklave.
        '''</summary>
        Friend ReadOnly Property practicePrime_Neg() As String
            Get
                Return ResourceManager.GetString("practicePrime_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kuss Idee Chance.
        '''</summary>
        Friend ReadOnly Property practicePrime_Pos() As String
            Get
                Return ResourceManager.GetString("practicePrime_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lpqmf Pxbzqnh.
        '''</summary>
        Friend ReadOnly Property practicePrime_Str() As String
            Get
                Return ResourceManager.GetString("practicePrime_Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BOSHAFT KORRUPT UNGERECHT GEHÄSSIG.
        '''</summary>
        Friend ReadOnly Property practiceTarget_Neg() As String
            Get
                Return ResourceManager.GetString("practiceTarget_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GEDULDIG ZÄRTLICH HUMORVOLL FLEISSIG.
        '''</summary>
        Friend ReadOnly Property practiceTarget_Pos() As String
            Get
                Return ResourceManager.GetString("practiceTarget_Pos", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
